Repository Mongen-Initiative/mongen-frontend, pull requests merged in 2021-04, with the labels that each got.

#28 Org profile - edit, preview and publish
  components/autocomplete/Countries.tsx
  components/forms/MainContact.tsx
  components/forms/OrganizationLocation.tsx
  components/forms/OrganizationLogo.tsx
  components/forms/OrganizationLogoUpload.tsx
  components/forms/OrganizationSummary.tsx
  components/templates/DetailedInfoModal.tsx
  components/templates/MainOrganizationList.tsx
  components/templates/newRecordSteps.tsx
  package-lock.json
  pages/[organizationId]/admin.tsx
  pages/[organizationId]/new-record.tsx
  pages/[organizationId]/profile.tsx
  pages/create-organization.tsx
Labels: enhancement

#31 Seo name in url instead of id
  components/services/OrganizationService.tsx
  components/templates/BasePage.tsx
  components/templates/CallToAction.tsx
  components/templates/DetailedInfoModal.tsx
  components/templates/MainOrganizationList.tsx
  package-lock.json
  package.json
  pages/[organizationName]/about.tsx
  pages/[organizationName]/admin.tsx
  pages/[organizationName]/child.tsx
  pages/[organizationName]/help.tsx
  pages/[organizationName]/index.tsx
  pages/[organizationName]/login-sponsor.tsx
  pages/[organizationName]/new-record.tsx
  pages/[organizationName]/payment.tsx
  pages/[organizationName]/profile.tsx
  pages/[organizationName]/sponsor.tsx
  pages/admin/all-organizations.tsx
Labels: Ready for review :1st_place_medal:

#30 Donor Organization Beneficiary integration
  components/services/DonorService.tsx
  components/templates/donationSteps.tsx
  pages/[organizationName]/payment.tsx
Labels: Ready for review :1st_place_medal:, enhancement

#32 Admin seo_name fixes + photo upload refactoring
  components/forms/OrganizationLogo.tsx
  components/forms/OrganizationLogoUpload.tsx
  components/forms/OrganizationPhotoId.tsx
  components/templates/DetailedInfoModal.tsx
  components/templates/ImageUpload.tsx
  package-lock.json
  package.json
  pages/[organizationName]/profile.tsx
  pages/admin/all-organizations.tsx
  pages/create-organization.tsx
Labels: Ready for review :1st_place_medal:
