Repository Mongen-Initiative/mongen-frontend, pull requests merged in 2021-01, with the labels that each got.

#6 Preparation for server rendering
  components/MuiTheme.ts
  components/templates/BasePage.tsx
  components/templates/CallToAction.tsx
  pages/[organisationName]/about.tsx
  pages/[organisationName]/child.tsx
  pages/[organisationName]/index.tsx
  pages/[organisationName]/newRecord.tsx
  pages/[organisationName]/orgProfile.tsx
  pages/[organisationName]/paymentForm.tsx
  pages/[organisationName]/sponsorProfile.tsx
  pages/index.tsx
  pages/loginAdmin.tsx
  pages/loginOrgMember.tsx
  pages/loginSponsor.tsx
Labels: Design improvements :hibiscus:

#11 Adding a table to view all organizations
  components/templates/OrgReviewModal.tsx
  package-lock.json
  package.json
  pages/[organisationName]/orgProfile.tsx
  pages/admin/all-organizations.tsx
  pages/admin/pending-organizations.tsx
Labels: Ready for review :1st_place_medal:

#12 UI improvements + list of collaborators
  components/templates/BasePage.tsx
  components/templates/CallToAction.tsx
  components/templates/OrgReviewModal.tsx
  package-lock.json
  package.json
  pages/[organisationName]/about.tsx
  pages/[organisationName]/admin.tsx
  pages/[organisationName]/orgProfile.tsx
  pages/[organisationName]/sponsorProfile.tsx
  pages/loginAdmin.tsx
Labels: Ready for review :1st_place_medal:

#8 Organization creation
  common/coreService.tsx
  common/mediaService.tsx
  components/autocomplete/Collaborator.tsx
  components/autocomplete/Countries.tsx
  components/forms/MainContact.tsx
  components/forms/OrganizationLocation.tsx
  components/forms/OrganizationNameVisionMission.tsx
  components/forms/OrganizationSummary.tsx
  components/forms/PhotoIDUpload.tsx
  components/forms/VerificationSelfieUpload.tsx
  components/services/MainContactService.tsx
  components/services/OrganizationService.tsx
  components/services/UploadService.tsx
  components/templates/MainOrganizationList.tsx
  components/templates/index.ts
  components/templates/organization/creationSteps.tsx
  data/Organizations.tsx
  package-lock.json
  package.json
  pages/createOrganization.tsx
  pages/index.tsx
Labels: New feature :sun_with_face:, Ready for review :1st_place_medal:, enhancement

#15 Renaming files + server side rendering for org page
  components/forms/MainContact.tsx
  components/forms/OrganizationLocation.tsx
  components/forms/OrganizationNameVisionMission.tsx
  components/forms/PhotoIDUpload.tsx
  components/templates/BasePage.tsx
  components/templates/CallToAction.tsx
  components/templates/DetailedInfoModal.tsx
  components/templates/Footer.tsx
  components/templates/MainOrganizationList.tsx
  next.config.js
  package-lock.json
  package.json
  pages/[organisationName]/about.tsx
  pages/[organisationName]/admin.tsx
  pages/[organisationName]/index.tsx
  pages/[organizationId]/about.tsx
  pages/[organizationId]/admin.tsx
  pages/[organizationId]/child.tsx
  pages/[organizationId]/index.tsx
  pages/[organizationId]/new-record.tsx
  pages/[organizationId]/payment.tsx
  pages/[organizationId]/profile.tsx
  pages/[organizationId]/sponsor.tsx
  pages/about-mongen.tsx
  pages/admin/all-organizations.tsx
  pages/admin/pending-organizations.tsx
  pages/create-organization.tsx
  pages/index.tsx
  pages/login-admin.tsx
  pages/login-member.tsx
  pages/login-sponsor.tsx
  tsconfig.json
Labels: Ready for review :1st_place_medal:

#16 Adding a new beneficiary form - POST to the backend
  components/forms/OrganizationNameVisionMission.tsx
  components/forms/OrganizationSummary.tsx
  components/forms/PhotoIDUpload.tsx
  components/services/BeneficiaryService.tsx
  components/templates/MainOrganizationList.tsx
  components/templates/newRecordSteps.tsx
  pages/[organizationId]/new-record.tsx
  pages/about-mongen.tsx
  pages/create-organization.tsx
  pages/index.tsx
Labels: Ready for review :1st_place_medal:
